specifications:
  'z_bins': [0.001, 0.418, 0.560, 0.678, 0.789, 0.900, 1.019, 1.155, 1.324, 1.576, 2.50]
  'zm': 0.9
  'ngamma': 1.5
  'ngal_sqarmin': 30
  'fout': 0.1
  'co': 1
  'cb': 1
  'sigma_o': 0.05
  'sigma_b': 0.05
  'zo': 0.1
  'zb': 0.0
  'fsky_GCph': 0.35
  'lmax_GCph': 750
  'lmin_GCph': 10
  'ellipt_error': 0.3
  'fsky_WL': 0.35
  'lmax_WL': 1500
  'lmin_WL': 10
  'kmax': 30.
  'bias_model': 'binned'
  'vary_ph_bias': 0.06
  'vary_IA_pars': 0.035
