repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.4  # Use the version from your GitHub Actions
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]

  - repo: https://github.com/psf/black
    rev: 24.8.0  # Use the version from your GitHub Actions
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: 5.13.2  # Use the version from your GitHub Actions
    hooks:
      - id: isort

