version: 2

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false

formats:
    - pdf
    - epub

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  #jobs:
  #  post_create_environment:
  #    - python -m pip install sphinx_rtd_theme

python:
  install:
    - requirements: requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - dev
