specifications:
  'spec_sigma_dz': 0.002
  'area_survey_spectro': 15000
  'kmax_GCsp': 0.25
  'kmin_GCsp': 0.001
  'z_bins_sp': 
    1: [0.90, 1.10]
    2: [1.10, 1.30]
    3: [1.30, 1.50]
    4: [1.50, 1.80]
  'dndOmegadz' : 
    1: 1815.0
    2: 1701.5
    3: 1410.0
    4: 940.97
  sp_bias_sample: 'g'
  sp_bias_model: 'linear_Qbias'
  sp_bias_root: 'b'
  sp_bias_parametrization:
    linear_Qbias:
      bg_1: 1.4614804
      bg_2: 1.6060949
      bg_3: 1.7464790
      bg_4: 1.8988660
      A2: -2.0
  shot_noise_model: 'constant'
  shot_noise_parametrization:
    constant:
      Ps_1: 0.0
      Ps_2: 0.0
      Ps_3: 0.0
      Ps_4: 0.0
