specifications:
  'z_bins_ph': [0.001, 0.418, 0.560, 0.678, 0.789, 0.900, 1.019, 1.155, 1.324, 1.576, 2.50]
  'zm': 1.1
  'ngamma': 1.25
  'ngal_sqarmin': 2.7
  photo_z_params:
    'fout': 0.1
    'co': 1
    'cb': 1
    'sigma_o': 0.05
    'sigma_b': 0.05
    'zo': 0.1
    'zb': 0.0
  'fsky_GCph': 0.1166
  'lmax_GCph': 750
  'lmin_GCph': 10
  'ellipt_error': 0.3
  'fsky_WL': 0.1166
  'lmax_WL': 3000
  'lmin_WL': 10
  'kmax': 30.
  'vary_ph_bias': 0.06
  'vary_IA_pars': 0.035
  ph_bias_model: 'binned'
  ph_bias_parametrization: 
    binned:
      keystr: 'b'
      generate_bias_keys: true
    binned_constant:
      keystr: 'b'
      generate_bias_keys: true
    sqrt:
      b0: 1.0
    flagship:
      A: 1.0
      B: 2.5
      C: 2.8
      D: 1.6
  IA_params:
    IA_model: 'eNLA'
    AIA: 1.72
    betaIA: 2.17
    etaIA: -0.41
