ACCURACY:
  'k_per_logint' : 50
  'AccuracyBoost' : 1
  'lAccuracyBoost' : 1
  'lSampleBoost' : 1
  'accurate_massive_neutrino_transfers' : False
  'MassiveNuMethod' : 0
NUMERICS:
  'zmax' : 5
  'zsamples': 100
  'extrap_kmax' : 100
COSMO_SETTINGS: 
# Massive neutrino baseline model
  'kmax' : 50
  'share_delta_neff' : True
  'halofit_version' : 'mead2020'
  'dark_energy_model' : 'ppf'
  'num_nu_massive' : 1
  'num_nu_massless' : 2.044
  'TCMB': 2.7255
  'WantTensors' : False
  'WantVectors' : False
  'Reion.Reionization' : False
  'WantCls' : False
  'Want_CMB' : False
  'Want_CMB_lensing': False
  'Want_cl_2D_array' : False
  'DoLateRadTruncation': True
  'DoLensing': False
LCDM:   
  'Omegak' : 0.
  'mnu' : 0.06  
  'YHe': 0.2454006
w0waCDM:
  'Omegak' : 0.
  'mnu' : 0.06  
  'YHe': 0.2454006