# Canonical profile: ../precision_profiles.yaml -> camb_hp
precision_profile_file: ../precision_profiles.yaml
precision_profile: camb_hp
LCDM:
  'Omegak' : 0.
  'tau' : 0.058
  'YHe' : 0.2454006
w0waCDM:
  'Omegak' : 0.
  'tau' : 0.058
  'YHe' : 0.2454006
