# Canonical profile: ../precision_profiles.yaml -> class_hp
precision_profile_file: ../precision_profiles.yaml
precision_profile: class_hp
LCDM :
  'Omega_k' : 0
  'tau_reio' : 0.058
  'YHe' : 0.2454006
w0waCDM :
  'Omega_Lambda' : 0.0
  'Omega_k' : 0
  'tau_reio' : 0.058
  'YHe' : 0.2454006
